baseURL = 'http://blog.z2z63.dev/'
defaultContentLanguage = "en"
languageCode = 'zh-CN'
title = "z2z63/Virtualfuture's Blog"

theme = "DoIt"
summaryLength = 70
hasCJKLanguage = true

enableGitInfo = true
[params]
  # DoIt theme version
  version = "0.3.X"
  gitRepo = "https://github.com/z2z63/z2z63.github.io"
  defaultTheme = "auto"
[params.math]
  enable = true
[param.page]
  # æ˜¯å¦åœ¨æ–‡ç« é¡µé¢æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£é“¾æ¥
  linkToMarkdown = true
  # é…ç½®ç¼–è¾‘æ–‡ç« çš„é“¾æ¥
  linkToEdit = true
[params.page.share]
  enable = true


[params.page.code]
  # é»˜è®¤å±•å¼€æ˜¾ç¤ºçš„ä»£ç è¡Œæ•°
  maxShownLines = 10
[params.page.comment]
 enable = true
  # Gitalk è¯„è®ºç³»ç»Ÿè®¾ç½®
  [params.page.comment.gitalk]
    enable = true
    owner = "z2z63"
    repo = "z2z63.github.io"
    clientId = "Ov23liMtTBdWPdBDJjuQ"
    clientSecret = "5c5e82f1b10ce323ce7efae32b1b8f0a87773577"
[params.page.toc]
  # æ˜¯å¦ä½¿ç”¨ç›®å½•
  enable = true
  # æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
  keepStatic = false
  # æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
  auto = true
[params.home.profile]
 avatarURL = "https://avatars.githubusercontent.com/z2z63"
 avatarLinkURL = "https://github.com/z2z63"
 title = "z2z63/Virtualfuture's Blog"
 subTitle = "cpp makes me crazy ğŸ˜‡ğŸ˜‡ğŸ˜‡"
 social = true

# ç½‘ç«™åˆ†æé…ç½®
[params.analytics]
  enable = true
  # Google Analytics
  [params.analytics.google]
    id = "G-48XH0QHHK3"
    # æ˜¯å¦åŒ¿ååŒ–ç”¨æˆ· IP
    anonymizeIP = false

[params.social]
  GitHub = "z2z63"
  Spotify = "31cruj6y7d62opb2cnyxrlbojx7y"
  Steam = "76561199180604882"
  Email = "vituralfuture@gmail.com"
  RSS = true
  
[params.search]
  enable = true
  type = "fuse"

[params.footer]
  enable = true
  hugo = true
  hostedOn = "GitHub Pages"
  copyright = true
  author = true
  since = 2023

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  # [[menu.main]]
  #   identifier = "tags"
  #   pre = ""
  #   post = ""
  #   name = "Tags"
  #   url = "/tags"
  #   title = ""
  #   weight = 2
  # [[menu.main]]
  #   identifier = "categories"
  #   pre = ""
  #   post = ""
  #   name = "Categories"
  #   url = "/categories"
  #   title = ""
  #   weight = 3
  [[menu.main]]
    identifier = "friends"
    pre = ""
    post = ""
    name = "Friends"
    url = "/friends"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about"
    title = ""
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
[outputs]
  home = ["HTML", "RSS", "JSON"]
# ä½œè€…é…ç½®
[params.author]
  name = "z2z63"
  email = "virtualfuture@gmail.com"
  link = "https://github.com/z2z63"
  avatar = "https://avatars.githubusercontent.com/z2z63"
# ç½‘ç«™åœ°å›¾é…ç½®
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
  # DoIt æ–°å¢ | 0.2.5 TypeIt é…ç½®
[params.typeit]
  # æ¯ä¸€æ­¥çš„æ‰“å­—é€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
  speed = 100
  # å…‰æ ‡çš„é—ªçƒé€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
  cursorSpeed = 1000
  # å…‰æ ‡çš„å­—ç¬¦ (æ”¯æŒ HTML æ ¼å¼)
  cursorChar = "|"
  # æ‰“å­—ç»“æŸä¹‹åå…‰æ ‡çš„æŒç»­æ—¶é—´ (å•ä½æ˜¯æ¯«ç§’, "-1" ä»£è¡¨æ— é™å¤§)
  duration = -1
